server:
  port: ${EUREKA_PORT:8761}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:192.168.0.119}:${EUREKA_ZONE_PORT:8761}/eureka/

spring:
  application:
    name: eureka-server
