server:
  port: ${EUREKA_PORT:8761}
  address: 47.95.214.100
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:47.95.214.100}:${EUREKA_ZONE_PORT:8762}/eureka/

spring:
  application:
    name: eureka-server
